# Men's Tennis Players of the Year

In [27]:
import pandas as pd
import sqlite3

Here's a fairly natural way to calculate the best men's and women's players for a given year. Simply give it to the player with the most victories in major tournaments. If there's a tie, then break the tie by giving it to the player, among those tied, with the most major *finals*. If there's still a tie, then look at major *semifinals*, etc. If two or more players are still tied, then we can start looking at performance in the Masters 1000 series. Let's work this out for men and women in the Open Era. (See the notebook in the womens_tennis folder for the latter.)

General note in what follows: I'll list what round of the majors was relevant to determining each year's "winner", but it doesn't follow from that indication that the winner was the *only* player to achieve that mark. For example, Stan Smith made it to three major quarterfinals in 1971, but there may have been others to achieve that. Smith is the best player (by our metric) of 1971 not simply because he made three major quarters but because he:

- won as many majors as anyone in 1971; and
- made it to as many finals in majors as anyone; and
- made it to as many semis in majors as anyone; and
- made it to more quarters in majors than anyone else.

## 1968

Note: We'll consider just three majors for this season since the Open Era began after the Australian Open.

Rod Laver (1) (2 major finals)

## 1969

Rod Laver (2) (4 major titles)

## 1970

Ken Rosewall (1) (2 major finals)

## 1971

Stan Smith (1) (3 major quarters)

## 1972

Ilie Nastase (1) (2 major finals)

## 1973

John Newcombe (1) (2 major titles)

## 1974

Jimmy Connors (1) (3 major titles)

## 1975

Bjorn Borg (1) (3 major quarters)

## 1976

Bjorn Borg (2) (2 major finals)

## 1977

Note: There were five majors this year as the Australian Open was moved to December.

Guillermo Vilas (1) (2 major titles)

## 1978

Bjorn Borg (3) (2 major titles)

## 1979

Bjorn Borg (4) (2 major titles)

## 1980

Bjorn Borg (5) (2 major titles)

## 1981

Johh McEnroe (1) (2 major titles)

## 1982

Jimmy Connors (2) (2 major titles)

## 1983

Mats Wilander (1) (2 major finals)

## 1984

John McEnroe (2 major titles)

## 1985

Ivan Lendl (1) (3 major semis)

## 1986

Note: There were only three majors this year as the Australian Open was moved back to January.

Ivan Lendl (2) (2 major titles)

## 1987

Ivan Lendl (3) (2 major titles)

## 1988

Mats Wilander (2) (3 major titles)

## 1989

Boris Becker (1) (2 major titles)

## 1990

Stefan Edberg (1) (2 major finals)

## 1991

Boris Becker (2) (3 major semis)

## 1992

Jim Courier (1) (2 major titles)

## 1993

Pete Sampras (1) (2 major titles)

## 1994

Pete Sampras (2) (2 major titles)

## 1995

Pete Sampras (3) (2 major titles)

## 1996

Pete Sampras (4) (2 major semis)

## 1997

Pete Sampras (5) (2 major titles)

## 1998

Pete Sampras (6) (3 major quarters)

## 1999

Andre Agassi (1) (2 major titles)

## 2000

Pete Sampras (7) (2 major finals)

## 2001

Andre Agassi (2) (2 major semis)

## 2002

Lleyton Hewitt (1) (2 major semis)

## 2003

Juan Carlos Ferrero (1) (2 major finals)

## 2004

Roger Federer (1) (3 major titles)

## 2005

Roger Federer (2) (2 major titles)

## 2006

Roger Federer (3) (3 major titles)

## 2007

Roger Federer (4) (3 major titles)

## 2008

Rafael Nadal (1) (2 major titles)

## 2009

Roger Federer (5) (2 major titles)

## 2010

Rafael Nadal (2) (3 major titles)

## 2011

Novak Djokovic (1) (3 major titles)

## 2012

Novak Djokovic (2) (3 major finals)

## 2013

Rafael Nadal (2) (2 major titles)

## 2014

Novak Djokovic (3) (3 major semis)

## 2015

Novak Djokovic (4) (3 major titles)

## 2016

Novak Djokovic (5) (2 major titles)

## 2017

Rafael Nadal (3) (3 major finals)

## 2018

Novak Djokovic (6) (2 major titles)

## 2019

Rafael Nadal (4) (3 major finals)

## 2020

Note: There were only three majors this year as Wimbledon was canceled because of COVID.

Dominic Thiem (1) (3 major quarters)

## 2021

Novak Djokovic (7) (3 major titles)

## 2022

Rafael Nadal (5) (2 major titles)

## 2023

Novak Djokovic (8) (3 major titles)

## 2024

Jannik Sinner (1) (3 major semis)

## 2025

Jannik Sinner (2) (3 major finals)

## Building a Data Table

Let's put this data in a pair of dictionaries, one for the men and one for the women.

In [5]:
moy_dict = {}

moy_dict['Rod Laver'] = [1968, 1969]
moy_dict['Ken Rosewall'] = [1970]
moy_dict['Stan Smith'] = [1971]
moy_dict['Ilie Nastase'] = [1972]
moy_dict['John Newcombe'] = [1973]
moy_dict['Jimmy Connors'] = [1974, 1982]
moy_dict['Bjorn Borg'] = [1975, 1976, 1978, 1979, 1980]
moy_dict['Guillermo Vilas'] = [1977]
moy_dict['John McEnroe'] = [1981, 1984]
moy_dict['Mats Wilander'] = [1983, 1988]
moy_dict['Ivan Lendl'] = [1985, 1986, 1987]
moy_dict['Boris Becker'] = [1989, 1991]
moy_dict['Stefan Edberg'] = [1990]
moy_dict['Jim Courier'] = [1992]
moy_dict['Pete Sampras'] = [1993, 1994, 1995, 1996, 1997, 1998, 2000]
moy_dict['Andre Agassi'] = [1999, 2001]
moy_dict['Lleyton Hewitt'] = [2002]
moy_dict['Juan Carlos Ferrero'] = [2003]
moy_dict['Roger Federer'] = [2004, 2005, 2006, 2007, 2009]
moy_dict['Rafael Nadal'] = [2008, 2010, 2013, 2017, 2019, 2022]
moy_dict['Novak Djokovic'] = [2011, 2012, 2014, 2015, 2016, 2018, 2021, 2023]
moy_dict['Dominic Thiem'] = [2020]
moy_dict['Jannik Sinner'] = [2024, 2025]

In [24]:
df = pd.DataFrame([(key, len(val)) for key, val in moy_dict.items()], columns=['Player', 'MOYs'])
df2 = df.sort_values(by='MOYs', ascending=False)

In [25]:
df2 = df2.reset_index(drop=True)
df2

                 Player  MOYs
0        Novak Djokovic     8
1          Pete Sampras     7
2          Rafael Nadal     6
3         Roger Federer     5
4            Bjorn Borg     5
5            Ivan Lendl     3
6             Rod Laver     2
7         Mats Wilander     2
8          Andre Agassi     2
9          Boris Becker     2
10         John McEnroe     2
11        Jimmy Connors     2
12        Jannik Sinner     2
13         Ken Rosewall     1
14        Stefan Edberg     1
15          Jim Courier     1
16      Guillermo Vilas     1
17       Lleyton Hewitt     1
18  Juan Carlos Ferrero     1
19        John Newcombe     1
20         Ilie Nastase     1
21           Stan Smith     1
22        Dominic Thiem     1

In [29]:
con = sqlite3.connect('../data/tennis.db')

In [30]:
df2.to_sql('moy', con=con)

In [31]:
pd.read_sql(
    """
    SELECT name
    FROM sqlite_schema
    WHERE type = 'table'
    """
    ,
    con
)

          name
0  mens_tennis
1          moy