In [1]:
import pandas as pd
import sqlite3

## 2026 Australian Open

In [2]:
# QFs
# Alcaraz d. De Minaur
# Zverev d. Tien
# Djokovic d. Musetti
# Sinner d. Shelton

# SFs
# Alcaraz d. Zverev
# Djokovic d. Sinner

# Fs
# Alcaraz d. Djokovic

In [3]:
con = sqlite3.connect('../data/tennis.db')

In [5]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Alcaraz, Carlos'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,365,"Alcaraz, Carlos",13,9,8,6,2,0,0,0,...,2,2,3,3,3,2,4,3,2,2

In [6]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 14,
    QF_Wins = 10,
    SF_Wins = 9,
    F_Wins = 7,
    Aus_QF_Appears = 3,
    Aus_QF_Wins = 1,
    Aus_SF_Wins = 1,
    Aus_F_Wins = 1
    
    WHERE Player = 'Alcaraz, Carlos'
    """
)

In [7]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'De Minaur, Alex'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,272,"De Minaur, Alex",6,0,0,0,1,0,0,0,...,0,0,1,0,0,0,3,0,0,0

In [8]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 7,
    Aus_QF_Appears = 2
    
    WHERE Player = 'De Minaur, Alex'
    """
)

In [9]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Zverev, Alexander'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,77,"Zverev, Alexander",15,9,3,0,4,3,1,0,...,1,0,0,0,0,0,4,2,1,0

In [10]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 16,
    QF_Wins = 10,
    Aus_QF_Appears = 5,
    Aus_QF_Wins = 4
    
    WHERE Player = 'Zverev, Alexander'
    """
)

In [11]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Tien, Learner'
    """
    ,
    con
)

Empty DataFrame
Columns: [index, Player, QF_Appears, QF_Wins, SF_Wins, F_Wins, Aus_QF_Appears, Aus_QF_Wins, Aus_SF_Wins, Aus_F_Wins, Fr_QF_Appears, Fr_QF_Wins, Fr_SF_Wins, Fr_F_Wins, Wim_QF_Appears, Wim_QF_Wins, Wim_SF_Wins, Wim_F_Wins, US_QF_Appears, US_QF_Wins, US_SF_Wins, US_F_Wins]
Index: []

[0 rows x 22 columns]

In [20]:
con.execute(
    """
    INSERT INTO mens_tennis
    VALUES (384, 'Tien, Learner', 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    """
)

In [21]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Djokovic, Novak'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,2,"Djokovic, Novak",64,53,37,24,15,12,10,10,...,7,3,16,14,10,7,14,14,10,4

In [22]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 65,
    QF_Wins = 54,
    SF_Wins = 38,
    Aus_QF_Appears = 16,
    Aus_QF_Wins = 13,
    Aus_SF_Wins = 11
    
    WHERE Player = 'Djokovic, Novak'
    """
)

In [24]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Musetti, Lorenzo'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,379,"Musetti, Lorenzo",2,2,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0

In [25]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 3,
    Aus_QF_Appears = 1
    
    WHERE Player = 'Musetti, Lorenzo'
    """
)

In [26]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Sinner, Jannik'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,343,"Sinner, Jannik",13,8,6,4,3,2,2,2,...,1,0,4,2,1,1,3,2,2,1

In [29]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 14,
    QF_Wins = 9,
    Aus_QF_Appears = 4,
    Aus_QF_Wins = 3
    
    WHERE Player = 'Sinner, Jannik'
    """
)

In [30]:
pd.read_sql(
    """
    SELECT *
    FROM mens_tennis
    WHERE Player = 'Shelton, Ben'
    """
    ,
    con
)

,index,Player,QF_Appears,QF_Wins,SF_Wins,F_Wins,Aus_QF_Appears,Aus_QF_Wins,Aus_SF_Wins,Aus_F_Wins,...,Fr_SF_Wins,Fr_F_Wins,Wim_QF_Appears,Wim_QF_Wins,Wim_SF_Wins,Wim_F_Wins,US_QF_Appears,US_QF_Wins,US_SF_Wins,US_F_Wins
0,375,"Shelton, Ben",4,2,0,0,2,1,0,0,...,0,0,1,0,0,0,1,1,0,0

In [31]:
con.execute(
    """
    UPDATE mens_tennis
    SET QF_Appears = 5,
    Aus_QF_Appears = 3
    
    WHERE Player = 'Shelton, Ben'
    """
)

In [32]:
con.commit()

In [33]:
con.close()